<?php
/**
 * Smart E-commerce do Brasil Tecnologia LTDA
 *
 * INFORMAÇÕES SOBRE LICENÇA
 *
 * Open Software License (OSL 3.0).
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Não edite este arquivo caso você pretenda atualizar este módulo futuramente
 * para novas versões.
 *
 * @category    Esmart
 * @package     Esmart_PayPalBrasil
 * @copyright   Copyright (c) 2013 Smart E-commerce do Brasil Tecnologia LTDA. (http://www.e-smart.com.br)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author      Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

/** @var $this Mage_Paypal_Block_Express_Shortcut */

$shortcutHtmlId = $this->getShortcutHtmlId();

$loader = $this->getLayout()->getBlock('paypalbrasil.express.loader');
$loaderId = $loader->getLoaderId();
?>
<div id="paypal-login">
<h2>Cliente Paypal</h2>
<p >Utilize sua conta Paypal e agilize sua compra.</p>
<br>
<p class="paypal-logo-shortcut">

<input type="image" id="<?php echo $shortcutHtmlId ?>"
       src="<?php echo $this->getImageUrl()?>"
       alt="<?php echo Mage::helper('paypal')->__('Checkout with PayPal');?>"
       title="<?php echo Mage::helper('paypal')->__('Checkout with PayPal');?>" />

<?php if ($this->getConfirmationUrl() || $this->getIsInCatalogProduct()): ?>
    <?php if ($this->getIsInCatalogProduct()): ?>
        <input type="hidden" id="pp_checkout_url" name="return_url" value="" />
    <?php endif; ?>


<?php endif; ?>
</p>
<?php if(!$this->isActiveIncontext()) :?>
<script type="text/javascript">
    //<![CDATA[

    Event.observe('<?php echo $shortcutHtmlId ?>', 'click', function(event) {
        Event.stop(event);
        var checkboxes = $$('.agree input[type="checkbox"]').length;

        if (checkboxes == 0) {
            EsmartPayPalBrasilProcessedCheckout();
            return true;
        }
        showWindowLightBox()
        $("agreementsBox").show();
        $$(".agreementsContainer")[0].addClassName('agreemShow');
    });

    function EsmartPayPalBrasilProcessedCheckout() {
        var confirmationUrl = '<?php echo $this->getCheckoutUrl() ?>';

        var checkboxes = $$('.agree input[type="checkbox"]').length;
        var checkboxesChecked = $$('.agree input[type="checkbox"]:checked').length;
        if (checkboxes > checkboxesChecked) {
            alert('<?php echo $this->__('Please agree to all Terms and Conditions before placing the order.')?>');
            return false;
        }

        $('<?php echo $loaderId ?>').show();

        <?php if ($this->getIsInCatalogProduct()): ?>
        $('pp_checkout_url').value = confirmationUrl;
        productAddToCartForm.submit($('product_addtocart_form'));
        <?php else: ?>
        window.location = confirmationUrl;
        <?php endif; ?>
    }
    //]]>
</script>
<?php endif; ?>
</div>
