<?php
/**
 * Smart E-commerce do Brasil Tecnologia LTDA
 *
 * INFORMAÇÕES SOBRE LICENÇA
 *
 * Open Software License (OSL 3.0).
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Não edite este arquivo caso você pretenda atualizar este módulo futuramente
 * para novas versões.
 *
 * @category    Esmart
 * @package     Esmart_PayPalBrasil
 * @copyright   Copyright (c) 2013 Smart E-commerce do Brasil Tecnologia LTDA. (http://www.e-smart.com.br)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author      Ricardo Martins <ricardo.martins@e-smart.com.br>
 * @author      Thiago H Oliveira <thiago.oliveira@e-smart.com.br>
 */
?>

<?php
$code = $this->getMethodCode();
?>
<ul class="form-list" id="payment_form_<?php echo $code?>" style="display:none;">
    <li>
        <div id="paypal_plus_loading" class="paypal_plus_loading" style="display:none;">
            <div class="paypal_plus_loading_img"></div>
        </div>
        <div id="paypal_plus_iframe"></div>
    </li>
</ul>
