<?php
/**
 * Smart E-commerce do Brasil Tecnologia LTDA
 *
 * INFORMAÇÕES SOBRE LICENÇA
 *
 * Open Software License (OSL 3.0).
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Não edite este arquivo caso você pretenda atualizar este módulo futuramente
 * para novas versões.
 *
 * @category    Esmart
 * @package     Esmart_PayPalBrasil
 * @copyright   Copyright (c) 2013 Smart E-commerce do Brasil Tecnologia LTDA. (http://www.e-smart.com.br)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author      Thiago H Oliveira <thiago.oliveira@e-smart.com.br>
 */
?>
<?php
/** @var Mage_Sales_Model_Quote_Payment $info */
$info = $this->getInfo();
?>
<p>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
</p>
<br />
 <p>
    ID da Transação:<?php echo $info->getAdditionalInformation('paypal_plus_sale_id'); ?>
</p>
<br />
<?php $cards[] = json_decode($info->getAdditionalInformation('paypal_plus_cards'), true); ?>
    <?php if (!empty($cards[0])): ?>
       
         <p>Cartão de crédito</p>

        <?php foreach ($cards as $card): ?>

            <?php if ($card['termQty'] == 1): ?>
                  
                <p> Pagamento em: 1x (à vista)</p>

            <?php else: ?>

                <small>
                    <strong>- Parcela(s): </strong>
                    <?php echo "{$card['termQty']}x de {$card['termValue']}"; ?> <br>
                    <strong>- Total: </strong><?php echo $card['total']; ?>
                </small>
                <br>

            <?php endif; ?>
        <?php endforeach; ?>  
    <?php else: ?>
      <p>
            <strong>Dados da Transação :</strong>
        </p>
         <strong>Cartão de crédito</strong> <br>
              <p> Pagamento em: 1x (à vista)</p>
    <?php endif; ?>